/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "cs-text": {
          DEFAULT: "var(--text)",
          10: "rgb(from var(--text) r g b / 0.1)",
          20: "rgb(from var(--text) r g b / 0.2)",
          30: "rgb(from var(--text) r g b / 0.3)",
          40: "rgb(from var(--text) r g b / 0.4)",
          50: "rgb(from var(--text) r g b / 0.5)",
          60: "rgb(from var(--text) r g b / 0.6)",
          70: "rgb(from var(--text) r g b / 0.7)",
          80: "rgb(from var(--text) r g b / 0.8)",
          90: "rgb(from var(--text) r g b / 0.9)",
        },
        "cs-background": {
          DEFAULT: "var(--background)",
          10: "rgb(from var(--background) r g b / 0.1)",
          20: "rgb(from var(--background) r g b / 0.2)",
          30: "rgb(from var(--background) r g b / 0.3)",
          40: "rgb(from var(--background) r g b / 0.4)",
          50: "rgb(from var(--background) r g b / 0.5)",
          60: "rgb(from var(--background) r g b / 0.6)",
          70: "rgb(from var(--background) r g b / 0.7)",
          80: "rgb(from var(--background) r g b / 0.8)",
          90: "rgb(from var(--background) r g b / 0.9)",
        },
        "cs-primary": {
          DEFAULT: "var(--primary)",
          10: "rgb(from var(--primary) r g b / 0.1)",
          20: "rgb(from var(--primary) r g b / 0.2)",
          30: "rgb(from var(--primary) r g b / 0.3)",
          40: "rgb(from var(--primary) r g b / 0.4)",
          50: "rgb(from var(--primary) r g b / 0.5)",
          60: "rgb(from var(--primary) r g b / 0.6)",
          70: "rgb(from var(--primary) r g b / 0.7)",
          80: "rgb(from var(--primary) r g b / 0.8)",
          90: "rgb(from var(--primary) r g b / 0.9)",
        },
        "cs-secondary": {
          DEFAULT: "var(--secondary)",
          10: "rgb(from var(--secondary) r g b / 0.1)",
          20: "rgb(from var(--secondary) r g b / 0.2)",
          30: "rgb(from var(--secondary) r g b / 0.3)",
          40: "rgb(from var(--secondary) r g b / 0.4)",
          50: "rgb(from var(--secondary) r g b / 0.5)",
          60: "rgb(from var(--secondary) r g b / 0.6)",
          70: "rgb(from var(--secondary) r g b / 0.7)",
          80: "rgb(from var(--secondary) r g b / 0.8)",
          90: "rgb(from var(--secondary) r g b / 0.9)",
        },
        "cs-accent": {
          DEFAULT: "var(--accent)",
          10: "rgb(from var(--accent) r g b / 0.1)",
          20: "rgb(from var(--accent) r g b / 0.2)",
          30: "rgb(from var(--accent) r g b / 0.3)",
          40: "rgb(from var(--accent) r g b / 0.4)",
          50: "rgb(from var(--accent) r g b / 0.5)",
          60: "rgb(from var(--accent) r g b / 0.6)",
          70: "rgb(from var(--accent) r g b / 0.7)",
          80: "rgb(from var(--accent) r g b / 0.8)",
          90: "rgb(from var(--accent) r g b / 0.9)",
        },
      },
    },
  },
  plugins: [],
};
